version: 0.0
os: linux
files:
  - source: /
    destination: /home/videowiki/public_html/videowiki
    overwrite: purge
permissions:
  - object: /home/ec2-user
    owner: videowiki
    group: videowiki
    type:
      - directory
      - file
hooks:

  ApplicationStart:
    - location: update.sh
      timeout: 120
      runas: videowiki