version: "3"
services:
  redis-server:
    image: 'redis'
    restart: "always"
  rabbitmq-server:
    image: 'rabbitmq'
    restart: "always"
  mongo-server:
    image: mongo:4.0.10

  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/home/videowiki
    restart: always
    depends_on:
      - redis-server
      - mongo-server
      - rabbitmq-server
